export const SET_COUNTRIES = "SET_COUNTRIES";
export const SET_COUNTRIES_FOUND = "SET_COUNTRIES_FOUND";
export const SET_CURRENT_COUNTRY = "SET_CURRENT_COUNTRY";
export const SET_BORDER_BY = "SET_BORDER_BY";
